/*
Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: infra.proto

package infra

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the parameters for Create API
type CreateParams struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateParams) Reset()         { *m = CreateParams{} }
func (m *CreateParams) String() string { return proto.CompactTextString(m) }
func (*CreateParams) ProtoMessage()    {}
func (*CreateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_infra_5e86bee458929dd0, []int{0}
}
func (m *CreateParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateParams.Unmarshal(m, b)
}
func (m *CreateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateParams.Marshal(b, m, deterministic)
}
func (dst *CreateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateParams.Merge(dst, src)
}
func (m *CreateParams) XXX_Size() int {
	return xxx_messageInfo_CreateParams.Size(m)
}
func (m *CreateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateParams proto.InternalMessageInfo

func (m *CreateParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the Create response
type CreateResp struct {
	ProviderID           string   `protobuf:"bytes,1,opt,name=providerID" json:"providerID,omitempty"`
	Nodename             string   `protobuf:"bytes,2,opt,name=nodename" json:"nodename,omitempty"`
	Error                int32    `protobuf:"varint,3,opt,name=error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResp) Reset()         { *m = CreateResp{} }
func (m *CreateResp) String() string { return proto.CompactTextString(m) }
func (*CreateResp) ProtoMessage()    {}
func (*CreateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_infra_5e86bee458929dd0, []int{1}
}
func (m *CreateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResp.Unmarshal(m, b)
}
func (m *CreateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResp.Marshal(b, m, deterministic)
}
func (dst *CreateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResp.Merge(dst, src)
}
func (m *CreateResp) XXX_Size() int {
	return xxx_messageInfo_CreateResp.Size(m)
}
func (m *CreateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResp proto.InternalMessageInfo

func (m *CreateResp) GetProviderID() string {
	if m != nil {
		return m.ProviderID
	}
	return ""
}

func (m *CreateResp) GetNodename() string {
	if m != nil {
		return m.Nodename
	}
	return ""
}

func (m *CreateResp) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

// The request message containing the parameters for Delete API
type DeleteParams struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteParams) Reset()         { *m = DeleteParams{} }
func (m *DeleteParams) String() string { return proto.CompactTextString(m) }
func (*DeleteParams) ProtoMessage()    {}
func (*DeleteParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_infra_5e86bee458929dd0, []int{2}
}
func (m *DeleteParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteParams.Unmarshal(m, b)
}
func (m *DeleteParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteParams.Marshal(b, m, deterministic)
}
func (dst *DeleteParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteParams.Merge(dst, src)
}
func (m *DeleteParams) XXX_Size() int {
	return xxx_messageInfo_DeleteParams.Size(m)
}
func (m *DeleteParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteParams.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteParams proto.InternalMessageInfo

func (m *DeleteParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the Delete response
type DeleteResp struct {
	Error                int32    `protobuf:"varint,1,opt,name=error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResp) Reset()         { *m = DeleteResp{} }
func (m *DeleteResp) String() string { return proto.CompactTextString(m) }
func (*DeleteResp) ProtoMessage()    {}
func (*DeleteResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_infra_5e86bee458929dd0, []int{3}
}
func (m *DeleteResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResp.Unmarshal(m, b)
}
func (m *DeleteResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResp.Marshal(b, m, deterministic)
}
func (dst *DeleteResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResp.Merge(dst, src)
}
func (m *DeleteResp) XXX_Size() int {
	return xxx_messageInfo_DeleteResp.Size(m)
}
func (m *DeleteResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResp proto.InternalMessageInfo

func (m *DeleteResp) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

// The request message containing the parameters for List API
type ListParams struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListParams) Reset()         { *m = ListParams{} }
func (m *ListParams) String() string { return proto.CompactTextString(m) }
func (*ListParams) ProtoMessage()    {}
func (*ListParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_infra_5e86bee458929dd0, []int{4}
}
func (m *ListParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListParams.Unmarshal(m, b)
}
func (m *ListParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListParams.Marshal(b, m, deterministic)
}
func (dst *ListParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListParams.Merge(dst, src)
}
func (m *ListParams) XXX_Size() int {
	return xxx_messageInfo_ListParams.Size(m)
}
func (m *ListParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ListParams.DiscardUnknown(m)
}

var xxx_messageInfo_ListParams proto.InternalMessageInfo

func (m *ListParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the List response
type ListResp struct {
	Message              string   `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResp) Reset()         { *m = ListResp{} }
func (m *ListResp) String() string { return proto.CompactTextString(m) }
func (*ListResp) ProtoMessage()    {}
func (*ListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_infra_5e86bee458929dd0, []int{5}
}
func (m *ListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResp.Unmarshal(m, b)
}
func (m *ListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResp.Marshal(b, m, deterministic)
}
func (dst *ListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResp.Merge(dst, src)
}
func (m *ListResp) XXX_Size() int {
	return xxx_messageInfo_ListResp.Size(m)
}
func (m *ListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListResp proto.InternalMessageInfo

func (m *ListResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// The request message containing metadata information
type Metadata struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_infra_5e86bee458929dd0, []int{6}
}
func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (dst *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(dst, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Metadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Metadata) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// The response message containing error code and message
type ErrorResp struct {
	Err                  int32    `protobuf:"varint,1,opt,name=err" json:"err,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorResp) Reset()         { *m = ErrorResp{} }
func (m *ErrorResp) String() string { return proto.CompactTextString(m) }
func (*ErrorResp) ProtoMessage()    {}
func (*ErrorResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_infra_5e86bee458929dd0, []int{7}
}
func (m *ErrorResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResp.Unmarshal(m, b)
}
func (m *ErrorResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResp.Marshal(b, m, deterministic)
}
func (dst *ErrorResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResp.Merge(dst, src)
}
func (m *ErrorResp) XXX_Size() int {
	return xxx_messageInfo_ErrorResp.Size(m)
}
func (m *ErrorResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResp.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResp proto.InternalMessageInfo

func (m *ErrorResp) GetErr() int32 {
	if m != nil {
		return m.Err
	}
	return 0
}

func (m *ErrorResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateParams)(nil), "infra.CreateParams")
	proto.RegisterType((*CreateResp)(nil), "infra.CreateResp")
	proto.RegisterType((*DeleteParams)(nil), "infra.DeleteParams")
	proto.RegisterType((*DeleteResp)(nil), "infra.DeleteResp")
	proto.RegisterType((*ListParams)(nil), "infra.ListParams")
	proto.RegisterType((*ListResp)(nil), "infra.ListResp")
	proto.RegisterType((*Metadata)(nil), "infra.Metadata")
	proto.RegisterType((*ErrorResp)(nil), "infra.ErrorResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InfragrpcClient is the client API for Infragrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InfragrpcClient interface {
	// Create infra
	Create(ctx context.Context, in *CreateParams, opts ...grpc.CallOption) (*CreateResp, error)
	// Delete infra
	Delete(ctx context.Context, in *DeleteParams, opts ...grpc.CallOption) (*DeleteResp, error)
	// List infra
	List(ctx context.Context, in *ListParams, opts ...grpc.CallOption) (*ListResp, error)
	// Share Metadata
	ShareMeta(ctx context.Context, in *Metadata, opts ...grpc.CallOption) (*ErrorResp, error)
}

type infragrpcClient struct {
	cc *grpc.ClientConn
}

func NewInfragrpcClient(cc *grpc.ClientConn) InfragrpcClient {
	return &infragrpcClient{cc}
}

func (c *infragrpcClient) Create(ctx context.Context, in *CreateParams, opts ...grpc.CallOption) (*CreateResp, error) {
	out := new(CreateResp)
	err := c.cc.Invoke(ctx, "/infra.Infragrpc/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infragrpcClient) Delete(ctx context.Context, in *DeleteParams, opts ...grpc.CallOption) (*DeleteResp, error) {
	out := new(DeleteResp)
	err := c.cc.Invoke(ctx, "/infra.Infragrpc/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infragrpcClient) List(ctx context.Context, in *ListParams, opts ...grpc.CallOption) (*ListResp, error) {
	out := new(ListResp)
	err := c.cc.Invoke(ctx, "/infra.Infragrpc/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infragrpcClient) ShareMeta(ctx context.Context, in *Metadata, opts ...grpc.CallOption) (*ErrorResp, error) {
	out := new(ErrorResp)
	err := c.cc.Invoke(ctx, "/infra.Infragrpc/ShareMeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InfragrpcServer is the server API for Infragrpc service.
type InfragrpcServer interface {
	// Create infra
	Create(context.Context, *CreateParams) (*CreateResp, error)
	// Delete infra
	Delete(context.Context, *DeleteParams) (*DeleteResp, error)
	// List infra
	List(context.Context, *ListParams) (*ListResp, error)
	// Share Metadata
	ShareMeta(context.Context, *Metadata) (*ErrorResp, error)
}

func RegisterInfragrpcServer(s *grpc.Server, srv InfragrpcServer) {
	s.RegisterService(&_Infragrpc_serviceDesc, srv)
}

func _Infragrpc_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfragrpcServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infra.Infragrpc/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfragrpcServer).Create(ctx, req.(*CreateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Infragrpc_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfragrpcServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infra.Infragrpc/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfragrpcServer).Delete(ctx, req.(*DeleteParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Infragrpc_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfragrpcServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infra.Infragrpc/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfragrpcServer).List(ctx, req.(*ListParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Infragrpc_ShareMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Metadata)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfragrpcServer).ShareMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infra.Infragrpc/ShareMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfragrpcServer).ShareMeta(ctx, req.(*Metadata))
	}
	return interceptor(ctx, in, info, handler)
}

var _Infragrpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "infra.Infragrpc",
	HandlerType: (*InfragrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Infragrpc_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Infragrpc_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Infragrpc_List_Handler,
		},
		{
			MethodName: "ShareMeta",
			Handler:    _Infragrpc_ShareMeta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "infra.proto",
}

func init() { proto.RegisterFile("infra.proto", fileDescriptor_infra_5e86bee458929dd0) }

var fileDescriptor_infra_5e86bee458929dd0 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x6d, 0xfa, 0x65, 0x33, 0x0a, 0xd6, 0xd5, 0x43, 0xc9, 0x41, 0xc2, 0xe2, 0xa1, 0x07, 0x29,
	0x52, 0x0f, 0xfe, 0x00, 0xab, 0x50, 0x50, 0x90, 0x78, 0x17, 0x56, 0x33, 0xd6, 0x80, 0xf9, 0x60,
	0xb2, 0x08, 0xfe, 0x4e, 0xff, 0x90, 0xcc, 0x6e, 0x76, 0xb3, 0xbd, 0xf4, 0x36, 0xf3, 0xe6, 0xcd,
	0xcb, 0xdb, 0x37, 0x81, 0xe3, 0xa2, 0xfa, 0x24, 0xb5, 0x6a, 0xa8, 0xd6, 0xb5, 0x98, 0x98, 0x46,
	0x4a, 0x38, 0xb9, 0x27, 0x54, 0x1a, 0x5f, 0x14, 0xa9, 0xb2, 0x15, 0x02, 0xc6, 0x95, 0x2a, 0x71,
	0x11, 0xa5, 0xd1, 0x32, 0xce, 0x4c, 0x2d, 0xdf, 0x00, 0x2c, 0x27, 0xc3, 0xb6, 0x11, 0x97, 0x00,
	0x0d, 0xd5, 0x3f, 0x45, 0x8e, 0xb4, 0xdd, 0x74, 0xbc, 0x00, 0x11, 0x09, 0xcc, 0xaa, 0x3a, 0x47,
	0xa3, 0x32, 0x34, 0x53, 0xdf, 0x8b, 0x0b, 0x98, 0x20, 0x51, 0x4d, 0x8b, 0x51, 0x1a, 0x2d, 0x27,
	0x99, 0x6d, 0xd8, 0xc3, 0x06, 0xbf, 0xf1, 0xa0, 0x07, 0x09, 0x60, 0x39, 0xc6, 0x83, 0xd7, 0x89,
	0x42, 0x9d, 0x14, 0xe0, 0xa9, 0x68, 0xf5, 0x01, 0x95, 0x2b, 0x98, 0x31, 0xc3, 0x68, 0x2c, 0xe0,
	0xa8, 0xc4, 0xb6, 0x55, 0x3b, 0x47, 0x71, 0xad, 0x7c, 0x84, 0xd9, 0x33, 0x6a, 0x95, 0x2b, 0xad,
	0x58, 0x45, 0xff, 0x36, 0x5e, 0x85, 0x6b, 0xaf, 0x3c, 0xec, 0x95, 0x19, 0x63, 0xbe, 0x79, 0x58,
	0x9c, 0x99, 0x5a, 0xde, 0x41, 0xfc, 0xc0, 0xc6, 0xcc, 0xe7, 0xe6, 0x30, 0x42, 0x72, 0x86, 0xb9,
	0x0c, 0x0d, 0x0c, 0xf7, 0x0c, 0xac, 0xff, 0x22, 0x88, 0xb7, 0x7c, 0x9e, 0x1d, 0x35, 0x1f, 0x62,
	0x0d, 0x53, 0x1b, 0xbf, 0x38, 0x5f, 0xd9, 0x0b, 0x86, 0x17, 0x4b, 0xce, 0xf6, 0x40, 0xfe, 0x96,
	0x1c, 0xf0, 0x8e, 0x8d, 0xcb, 0xef, 0x84, 0x09, 0xfb, 0x9d, 0x3e, 0x52, 0x39, 0x10, 0xd7, 0x30,
	0xe6, 0x70, 0x84, 0x1b, 0xf6, 0x59, 0x26, 0xa7, 0x01, 0xd4, 0xb1, 0x6f, 0x20, 0x7e, 0xfd, 0x52,
	0x84, 0x9c, 0x94, 0x70, 0x73, 0x17, 0x5b, 0x32, 0xef, 0x00, 0xff, 0x7e, 0x39, 0x78, 0x9f, 0x9a,
	0x1f, 0xef, 0xf6, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x32, 0x75, 0x32, 0xa3, 0x87, 0x02, 0x00, 0x00,
}
