// Code generated by protoc-gen-go. DO NOT EDIT.
// source: infra.proto

package infra

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the parameters for Create API
type CreateParams struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateParams) Reset()         { *m = CreateParams{} }
func (m *CreateParams) String() string { return proto.CompactTextString(m) }
func (*CreateParams) ProtoMessage()    {}
func (*CreateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_infra_78c149f634d82c9a, []int{0}
}
func (m *CreateParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateParams.Unmarshal(m, b)
}
func (m *CreateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateParams.Marshal(b, m, deterministic)
}
func (dst *CreateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateParams.Merge(dst, src)
}
func (m *CreateParams) XXX_Size() int {
	return xxx_messageInfo_CreateParams.Size(m)
}
func (m *CreateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateParams proto.InternalMessageInfo

func (m *CreateParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the Create response
type CreateResp struct {
	ProviderID           string   `protobuf:"bytes,1,opt,name=providerID" json:"providerID,omitempty"`
	Nodename             string   `protobuf:"bytes,2,opt,name=nodename" json:"nodename,omitempty"`
	Error                int32    `protobuf:"varint,3,opt,name=error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResp) Reset()         { *m = CreateResp{} }
func (m *CreateResp) String() string { return proto.CompactTextString(m) }
func (*CreateResp) ProtoMessage()    {}
func (*CreateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_infra_78c149f634d82c9a, []int{1}
}
func (m *CreateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResp.Unmarshal(m, b)
}
func (m *CreateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResp.Marshal(b, m, deterministic)
}
func (dst *CreateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResp.Merge(dst, src)
}
func (m *CreateResp) XXX_Size() int {
	return xxx_messageInfo_CreateResp.Size(m)
}
func (m *CreateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResp proto.InternalMessageInfo

func (m *CreateResp) GetProviderID() string {
	if m != nil {
		return m.ProviderID
	}
	return ""
}

func (m *CreateResp) GetNodename() string {
	if m != nil {
		return m.Nodename
	}
	return ""
}

func (m *CreateResp) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

// The request message containing the parameters for Delete API
type DeleteParams struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteParams) Reset()         { *m = DeleteParams{} }
func (m *DeleteParams) String() string { return proto.CompactTextString(m) }
func (*DeleteParams) ProtoMessage()    {}
func (*DeleteParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_infra_78c149f634d82c9a, []int{2}
}
func (m *DeleteParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteParams.Unmarshal(m, b)
}
func (m *DeleteParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteParams.Marshal(b, m, deterministic)
}
func (dst *DeleteParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteParams.Merge(dst, src)
}
func (m *DeleteParams) XXX_Size() int {
	return xxx_messageInfo_DeleteParams.Size(m)
}
func (m *DeleteParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteParams.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteParams proto.InternalMessageInfo

func (m *DeleteParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the Delete response
type DeleteResp struct {
	Error                int32    `protobuf:"varint,1,opt,name=error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResp) Reset()         { *m = DeleteResp{} }
func (m *DeleteResp) String() string { return proto.CompactTextString(m) }
func (*DeleteResp) ProtoMessage()    {}
func (*DeleteResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_infra_78c149f634d82c9a, []int{3}
}
func (m *DeleteResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResp.Unmarshal(m, b)
}
func (m *DeleteResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResp.Marshal(b, m, deterministic)
}
func (dst *DeleteResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResp.Merge(dst, src)
}
func (m *DeleteResp) XXX_Size() int {
	return xxx_messageInfo_DeleteResp.Size(m)
}
func (m *DeleteResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResp proto.InternalMessageInfo

func (m *DeleteResp) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

// The request message containing the parameters for List API
type ListParams struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListParams) Reset()         { *m = ListParams{} }
func (m *ListParams) String() string { return proto.CompactTextString(m) }
func (*ListParams) ProtoMessage()    {}
func (*ListParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_infra_78c149f634d82c9a, []int{4}
}
func (m *ListParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListParams.Unmarshal(m, b)
}
func (m *ListParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListParams.Marshal(b, m, deterministic)
}
func (dst *ListParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListParams.Merge(dst, src)
}
func (m *ListParams) XXX_Size() int {
	return xxx_messageInfo_ListParams.Size(m)
}
func (m *ListParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ListParams.DiscardUnknown(m)
}

var xxx_messageInfo_ListParams proto.InternalMessageInfo

func (m *ListParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the List response
type ListResp struct {
	Message              string   `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResp) Reset()         { *m = ListResp{} }
func (m *ListResp) String() string { return proto.CompactTextString(m) }
func (*ListResp) ProtoMessage()    {}
func (*ListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_infra_78c149f634d82c9a, []int{5}
}
func (m *ListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResp.Unmarshal(m, b)
}
func (m *ListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResp.Marshal(b, m, deterministic)
}
func (dst *ListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResp.Merge(dst, src)
}
func (m *ListResp) XXX_Size() int {
	return xxx_messageInfo_ListResp.Size(m)
}
func (m *ListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListResp proto.InternalMessageInfo

func (m *ListResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateParams)(nil), "infra.CreateParams")
	proto.RegisterType((*CreateResp)(nil), "infra.CreateResp")
	proto.RegisterType((*DeleteParams)(nil), "infra.DeleteParams")
	proto.RegisterType((*DeleteResp)(nil), "infra.DeleteResp")
	proto.RegisterType((*ListParams)(nil), "infra.ListParams")
	proto.RegisterType((*ListResp)(nil), "infra.ListResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InfragrpcClient is the client API for Infragrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InfragrpcClient interface {
	// Create infra
	Create(ctx context.Context, in *CreateParams, opts ...grpc.CallOption) (*CreateResp, error)
	// Delete infra
	Delete(ctx context.Context, in *DeleteParams, opts ...grpc.CallOption) (*DeleteResp, error)
	// List infra
	List(ctx context.Context, in *ListParams, opts ...grpc.CallOption) (*ListResp, error)
}

type infragrpcClient struct {
	cc *grpc.ClientConn
}

func NewInfragrpcClient(cc *grpc.ClientConn) InfragrpcClient {
	return &infragrpcClient{cc}
}

func (c *infragrpcClient) Create(ctx context.Context, in *CreateParams, opts ...grpc.CallOption) (*CreateResp, error) {
	out := new(CreateResp)
	err := c.cc.Invoke(ctx, "/infra.Infragrpc/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infragrpcClient) Delete(ctx context.Context, in *DeleteParams, opts ...grpc.CallOption) (*DeleteResp, error) {
	out := new(DeleteResp)
	err := c.cc.Invoke(ctx, "/infra.Infragrpc/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infragrpcClient) List(ctx context.Context, in *ListParams, opts ...grpc.CallOption) (*ListResp, error) {
	out := new(ListResp)
	err := c.cc.Invoke(ctx, "/infra.Infragrpc/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InfragrpcServer is the server API for Infragrpc service.
type InfragrpcServer interface {
	// Create infra
	Create(context.Context, *CreateParams) (*CreateResp, error)
	// Delete infra
	Delete(context.Context, *DeleteParams) (*DeleteResp, error)
	// List infra
	List(context.Context, *ListParams) (*ListResp, error)
}

func RegisterInfragrpcServer(s *grpc.Server, srv InfragrpcServer) {
	s.RegisterService(&_Infragrpc_serviceDesc, srv)
}

func _Infragrpc_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfragrpcServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infra.Infragrpc/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfragrpcServer).Create(ctx, req.(*CreateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Infragrpc_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfragrpcServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infra.Infragrpc/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfragrpcServer).Delete(ctx, req.(*DeleteParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Infragrpc_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfragrpcServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infra.Infragrpc/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfragrpcServer).List(ctx, req.(*ListParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _Infragrpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "infra.Infragrpc",
	HandlerType: (*InfragrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Infragrpc_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Infragrpc_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Infragrpc_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "infra.proto",
}

func init() { proto.RegisterFile("infra.proto", fileDescriptor_infra_78c149f634d82c9a) }

var fileDescriptor_infra_78c149f634d82c9a = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0xac, 0xa1, 0x29, 0xed, 0x80, 0x84, 0x58, 0x38, 0x44, 0x39, 0xa0, 0xc8, 0xe2, 0xd0, 0x03,
	0xea, 0xa1, 0x3c, 0x81, 0x5e, 0x2a, 0x71, 0x40, 0x79, 0x00, 0x92, 0xa1, 0x4b, 0x15, 0x89, 0xc4,
	0xd1, 0x3a, 0xe2, 0x3f, 0xfc, 0x14, 0xd9, 0x26, 0xa9, 0xb9, 0xe4, 0xe6, 0xd9, 0x9d, 0x1d, 0xcd,
	0x8c, 0x71, 0x59, 0xb7, 0x9f, 0x62, 0x36, 0x9d, 0xd8, 0xde, 0x52, 0x16, 0x80, 0xd6, 0xb8, 0x7a,
	0x16, 0x36, 0x3d, 0xbf, 0x1a, 0x31, 0x8d, 0x23, 0xc2, 0xbc, 0x35, 0x0d, 0xe7, 0xaa, 0x54, 0xeb,
	0x55, 0x15, 0xde, 0xfa, 0x0d, 0x88, 0x9c, 0x8a, 0x5d, 0x47, 0xf7, 0x40, 0x27, 0xf6, 0xbb, 0x3e,
	0xb0, 0xec, 0x77, 0x7f, 0xbc, 0x64, 0x42, 0x05, 0x96, 0xad, 0x3d, 0x70, 0x50, 0x39, 0x0b, 0xdb,
	0x11, 0xd3, 0x1d, 0x32, 0x16, 0xb1, 0x92, 0x9f, 0x97, 0x6a, 0x9d, 0x55, 0x11, 0x78, 0x0f, 0x3b,
	0xfe, 0xe2, 0x49, 0x0f, 0x1a, 0x88, 0x9c, 0xe0, 0x61, 0xd4, 0x51, 0xa9, 0x4e, 0x09, 0xbc, 0xd4,
	0xae, 0x9f, 0x50, 0x79, 0xc0, 0xd2, 0x33, 0x82, 0x46, 0x8e, 0x8b, 0x86, 0x9d, 0x33, 0xc7, 0x81,
	0x32, 0xc0, 0xed, 0x8f, 0xc2, 0x6a, 0xef, 0xdb, 0x39, 0x4a, 0xf7, 0x41, 0x5b, 0x2c, 0x62, 0x7a,
	0xba, 0xdd, 0xc4, 0x02, 0xd3, 0xc2, 0x8a, 0x9b, 0x7f, 0x43, 0xaf, 0xac, 0x67, 0xfe, 0x26, 0xba,
	0x1d, 0x6f, 0xd2, 0x80, 0xe3, 0xcd, 0x29, 0x91, 0x9e, 0xd1, 0x23, 0xe6, 0xde, 0x1b, 0x0d, 0xcb,
	0x53, 0x94, 0xe2, 0x3a, 0x19, 0x45, 0xf6, 0xfb, 0x22, 0xfc, 0xe2, 0xd3, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x98, 0xca, 0x5b, 0x24, 0xd4, 0x01, 0x00, 0x00,
}
